site_name: BioStudies Index Service

theme:
  name: material

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Collections Registry: collections-registry.md
  - Lucene indexes: lucene-indexes.md

plugins:
  - search
  - mermaid2:
      arguments:
        theme: default

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format