apiVersion: v1
kind: Service
metadata:
  name: indexer-reader-svc
  namespace: biostudies-index-service-dev
spec:
  selector:
    app: indexer
    role: reader
  ports:
    - protocol: TCP
      port: 80              # External port (what other services/users connect to)
      targetPort: 8080      # Container port (indexer-reader listens here)
      nodePort: 31301      # Different node port for readers
  type: NodePort
