apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indexer-writer-pvc
  namespace: biostudies-index-service-dev
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage